# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo_title', models.CharField(max_length=100)),
                ('photo_pic', models.FileField(upload_to='')),
            ],
        ),
    ]
