# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='note',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
